FROM amazonlinux:1
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

# Install epel repository
RUN rpm -ihv http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

RUN yum makecache fast && \
    yum -y install deltarpm && \
    yum -y update && \
    yum -y install sysvinit initscripts openssh-server openssh-clients --enablerepo=epel && \
    yum clean metadata && \
    yum clean all

CMD ["/sbin/init"]
