FROM centos:6
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

RUN yum -y install epel-release
RUN yum -y install git sudo openssh-server openssh-clients

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

VOLUME ["/sys/fs/cgroup"]

CMD ["/sbin/init"]
