FROM debian:8
MAINTAINER diodonfrost <diodon.frost@diodonfrost.me>

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    git \
    apt-transport-https \
    curl \
    openssh-server openssh-client \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/sbin/init"]
